### ISSUE TITLE
Stuck in conda installation

### ISSUE THREAD

**Issue by alvesmjoel** [antonisdim/haystack#6]
Conda installation unsuccessful when using the command provided in the instructions: `conda install -c bioconda haystac.` Returns the following then gets stuck indefinitely on "Collecting package metadata

_Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): |_

System: Ubuntu 14.04.5 LTS

**Comment by Pkaps25** [comment]
Can you check if the command `conda install -c conda-forge -c bioconda haystac` works? I experienced the same issue and this fix helped.

**Comment by alvesmjoel** [comment]
Thanks, I have tried both suggestions, but the first still gets stuck in the same step and the second prompt an installation error. 

> Can you check if the command `conda install -c conda-forge -c bioconda haystac` works? I experienced the same issue and this fix helped.
> 
> If that doesn't work, you could also try `python -m pip install git+https://github.com/antonisdim/haystac.git`. This was from the file `example/tutorial_example.sh`

**Comment by antonisdim** [comment]
Hello @alvesmjoel, 

I hope you are doing great and apologies for the super delayed response !

We have tried to reduce the list of dependencies needed for the installation of ``haystac``. Could you possibly follow the updated installation instructions provided on ``readthedocs``, and try to install the latest version of ``haystac`` from ``github`` please ? 

Please let us know if you face any other issues !

Best, 
Antony
